# Generated by Django 5.0 on 2023-12-17 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0003_collection_date_modified_collection_is_private_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='description',
            field=models.CharField(default='This is the description of an old collection', max_length=256),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='collection',
            name='type',
            field=models.IntegerField(choices=[(0, 'Normal'), (1, 'Favorite'), (2, 'Owned'), (3, 'Playing'), (4, 'Completed')], default=0),
        ),
    ]
