# Generated by Django 5.0 on 2023-12-08 04:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('game', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Platform',
            fields=[
                ('platform_id', models.AutoField(primary_key=True, serialize=False)),
                ('platform', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='UserGamePlatform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Score', models.IntegerField()),
                ('status', models.CharField(choices=[('PTP', 'Planning to Play'), ('OH', 'On Hold'), ('CP', 'Currently Playing'), ('COM', 'Completed'), ('DR', 'Dropped')], max_length=3)),
                ('review', models.TextField()),
                ('game_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.game')),
                ('platform_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stats.platform')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user')),
            ],
        ),
    ]
