# Generated by Django 5.0 on 2023-12-17 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usergameplatform',
            old_name='Score',
            new_name='score',
        ),
    ]
