# Generated by Django 4.2.5 on 2023-12-28 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0002_rename_score_usergameplatform_score'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usergameplatform',
            name='platform_id',
        ),
    ]
